### PR TITLE
fix: #8. Defer to browsers for incorrect callback type

### LINKED ISSUE #8: Polyfill raises exception where native behavior does not
Consider this code:

```js
document.addEventListener('click', 'key', {})
```

This is invalid use of `addEventListener` because the 2nd argument isn't a function. It doesn't, however, cause an exception with native browser behavior, since browsers will just silently ignore the invalid callback.

When the polyfill is active, this does cause an exception:

```
TypeError: WeakMap.prototype.set: 'key' is not an object
```

This exposes an implemenetation detail of the polyfill. The correct behavior would be to silence this exception. Perhaps `weakmap.set(...)` could be wrapped in a `try..catch`.

### PR DESCRIPTION
**Pull request by keithamus**
Fixes #8

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -16,7 +16,8 @@ var enhance = module.exports = function enhance(proto) {
 
   var listeners = new WeakMap()
   proto.addEventListener = function(name, originalCallback, optionsOrCapture) {
-    if (optionsOrCapture === undefined || optionsOrCapture === true || optionsOrCapture === false) {
+    var expectedOriginalCallback = Boolean(originalCallback && typeof originalCallback === 'function' || typeof originalCallback === 'object')
+    if (!expectedOriginalCallback || optionsOrCapture === undefined || optionsOrCapture === true || optionsOrCapture === false) {
```
Comment (mislav) [inline src/index.js]: Could the condition be rewritten as:

```js
if (optionsOrCapture === undefined || optionsOrCapture === true || optionsOrCapture === false || !Boolean(originalCallback && typeof originalCallback === 'function' || typeof originalCallback === 'object'))
```

That way the `typeof` checks are avoided in the happy path where the `optionsOrCapture === undefined` short-cirtuits the rest of the expression.

Comment (keithamus) [reply src/index.js]: Rewrote it, but the linter doesn't like `!Boolean(...)` so I had to tweak the conditions a little bit.
